// <auto-generated />
using System;
using DeMogioHang.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeMogioHang.Migrations
{
    [DbContext(typeof(DemoGHAppDbcontext))]
    partial class DemoGHAppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeMogioHang.Models.GioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("gioHangs");
                });

            modelBuilder.Entity("DeMogioHang.Models.GiohangChitiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GioHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GioHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("giohangChitiets");
                });

            modelBuilder.Entity("DeMogioHang.Models.Product", b =>
                {
                    b.Property<Guid>("SpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DeMogioHang.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeMogioHang.Models.GioHang", b =>
                {
                    b.HasOne("DeMogioHang.Models.User", "Users")
                        .WithOne("GioHangs")
                        .HasForeignKey("DeMogioHang.Models.GioHang", "UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DeMogioHang.Models.GiohangChitiet", b =>
                {
                    b.HasOne("DeMogioHang.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("GioHangId");

                    b.HasOne("DeMogioHang.Models.Product", "Product")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("SanPhamId");

                    b.Navigation("GioHang");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DeMogioHang.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("DeMogioHang.Models.Product", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("DeMogioHang.Models.User", b =>
                {
                    b.Navigation("GioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
